#!/bin/bash

source .env
export FLASK_HOST SECRET_KEY
export OVERMIND_AUTO_RESTART PROXY_URL
export REDIS_HOST REDIS_PASSWORD
export LINE_LOGIN_CLIENT_ID LINE_LOGIN_SECRET
export LINE_NOTIFY_CLIENT_SECRET LINE_NOTIFY_CLIENT_ID
export TINYURL_TOKEN
export SENTRY_DSN ROOK_TOKEN
export APP_ENV
export TEST_USER_SUB
exec "$@"
